version: '3.8'

services:
    nginx:
      container_name: nginx
      build:
        context: ./
        dockerfile: docker/nginx/Dockerfile
        target: local
      ports:
        - '80:80'
        - '443:443'
      volumes:
        - ./public:/var/www/public
      environment:
        PHP_HOST: php
        LOG_FORMAT: '/dev/stdout json_combined'
      depends_on:
        - php

    php:
        container_name: php
        build:
            context: ./
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/var/www
        extra_hosts:
          - host.docker.internal:host-gateway

    db:
        image: mysql:5.7
        platform: linux/amd64
        container_name: db
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: laravel
          MYSQL_USER: mysql
          MYSQL_PASSWORD: mysql
        ports:
            - "3306:3306"
        volumes:
            - mysql:/var/lib/mysql:delegated
        extra_hosts:
          - host.docker.internal:host-gateway

volumes:
  mysql:
  php:
